### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mkuratczyk** [pivotal-cf/go-pivnet#19]
Hi. When using pcf-pipelines, which in turn use Concourse pivnet-resource which uses go-pivnet, I have the resource crashing while downloading a tile:
```
Downloading: 'PCF Elastic Runtime' to file: '/tmp/build/get/cf-1.12.9-build.3.pivotal'
201.59 MiB / 8.01 GiB [>---------------------------------------]   2.46% 31m43spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x62e2bc]
goroutine 113 [running]:
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download.Client.retryableRequest(0x848fa0, 0xc42005f560, 0x849e20, 0xc4200129b8, 0x84e180, 0xc420390f20, 0x84b120, 0xc4200be580, 0xc42052a000, 0x233, ...)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download/downloader.go:165 +0x27c
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download.Client.Get.func1(0x8, 0x70a688)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download/downloader.go:93 +0xb3
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420242ec0, 0xc42053c000)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```
The error is repeatable - crashed 7 time for me so far (never succeeded) but it fails at different times during the download (sometimes after just 201MBs like in the error above, sometimes after 4GB).

Your help appreciated,

**Comment by robdimsdale** [comment]
I think this is related to https://github.com/pivotal-cf/pivnet-resource/issues/84

**Comment by aussielunix** [comment]
Stumbled on this today and tracked it down to concourse workers were running out of disk.
The fix for us was:

Apply this ops file to your concourse and set `worker_ephemeral_disk` to a value from cloud config.
https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/operations/worker-ephemeral-disk.yml

**Comment by pnikonowicz** [comment]
We are now checking if the disk is full before downloading. closing issue.
